name: Go SDK Test 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.16'  

    - name: Navigate to subdirectory and run go mod tidy
      run: |
        cd ./test
        go mod tidy

    - name: Run Go Tests
      working-directory: ./test
      run: go test -v 
